const vocab_cu1 = [
    {"word": "drought", "type": "n", "vietnamese": "hạn hán"},
    {"word": "crop", "type": "n", "vietnamese": "cây trồng"},
    {"word": "herbicide", "type": "n", "vietnamese": "thuốc diệt cỏ"},
    {"word": "agricultural", "type": "adj", "vietnamese": "thuộc về nông nghiệp"},
    {"word": "tractor", "type": "n", "vietnamese": "máy kéo (nông nghiệp)"},
    {"word": "plough", "type": "n", "vietnamese": "cái cày"},
    {"word": "estimate", "type": "n", "vietnamese": "sự ước tính"},
    {"word": "method", "type": "n", "vietnamese": "phương pháp"},
    {"word": "implement", "type": "v", "vietnamese": "thực hiện, triển khai"},
    {"word": "sacrifice", "type": "v", "vietnamese": "hi sinh"},
    {"word": "horizontal", "type": "adj", "vietnamese": "theo chiều ngang"},
    {"word": "evolve", "type": "v", "vietnamese": "tiến hóa"},
    {"word": "artificial", "type": "adj", "vietnamese": "nhân tạo"},
    {"word": "light", "type": "n", "vietnamese": "ánh sáng"},
    {"word": "natural", "type": "adj", "vietnamese": "tự nhiên"},
    {"word": "overhead", "type": "adj", "vietnamese": "ở phía trên"},
    {"word": "aspiration", "type": "n", "vietnamese": "khát vọng"},
    {"word": "stack", "type": "v", "vietnamese": "xếp chồng"},
    {"word": "tray", "type": "n", "vietnamese": "khay"},
    {"word": "vertical", "type": "adj", "vietnamese": "theo chiều dọc"},
    {"word": "farming", "type": "n", "vietnamese": "sự canh tác"},
    {"word": "potential", "type": "adj", "vietnamese": "tiềm năng"},
    {"word": "advantage", "type": "n", "vietnamese": "lợi thế"},
    {"word": "probable", "type": "adj", "vietnamese": "có khả năng xảy ra"},
    {"word": "development", "type": "n", "vietnamese": "sự phát triển"},
    {"word": "infectious", "type": "adj", "vietnamese": "truyền nhiễm"},
    {"word": "disease", "type": "n", "vietnamese": "bệnh"},
    {"word": "urban", "type": "adj", "vietnamese": "thuộc đô thị"},
    {"word": "centre", "type": "n", "vietnamese": "trung tâm"},
    {"word": "sort", "type": "n", "vietnamese": "loại"},
    {"word": "work", "type": "n", "vietnamese": "công việc"},
    {"word": "rest", "type": "n", "vietnamese": "phần còn lại"},
    {"word": "conversation", "type": "n", "vietnamese": "cuộc trò chuyện"},
    {"word": "special", "type": "adj", "vietnamese": "đặc biệt"},
    {"word": "clinic", "type": "n", "vietnamese": "phòng khám"},
    {"word": "branch", "type": "n", "vietnamese": "chi nhánh"},
    {"word": "devote", "type": "v", "vietnamese": "dành (thời gian), cống hiến"},
    {"word": "midday", "type": "n", "vietnamese": "giữa trưa"},
    {"word": "sign", "type": "v", "vietnamese": "ký tên"},
    {"word": "autograph", "type": "n", "vietnamese": "chữ ký"},
    {"word": "entrant", "type": "n", "vietnamese": "thí sinh, người tham gia"},
    {"word": "muscle", "type": "n", "vietnamese": "cơ bắp"},
    {"word": "tone", "type": "n", "vietnamese": "âm điệu, sắc thái"},
    {"word": "advert", "type": "n", "vietnamese": "quảng cáo, thông báo"},
    {"word": "whole", "type": "adj", "vietnamese": "toàn bộ"},
    {"word": "weekend", "type": "n", "vietnamese": "cuối tuần"},
    {"word": "section", "type": "n", "vietnamese": "phần, mục"},
    {"word": "appearance", "type": "n", "vietnamese": "ngoại hình, sự xuất hiện"},
    {"word": "modify", "type": "v", "vietnamese": "sửa đổi"},
    {"word": "manipulate", "type": "v", "vietnamese": "thao túng, vận dụng"},
    {"word": "realistic", "type": "adj", "vietnamese": "thực tế"},
    {"word": "situation", "type": "n", "vietnamese": "tình huống"},
    {"word": "handle", "type": "v", "vietnamese": "xử lý"},
    {"word": "dialogue", "type": "n", "vietnamese": "hội thoại"},
    {"word": "mismatch", "type": "n", "vietnamese": "sự không phù hợp"},
    {"word": "specific", "type": "adj", "vietnamese": "cụ thể"},
    {"word": "purpose", "type": "n", "vietnamese": "mục đích"},
    {"word": "centre", "type": "n", "vietnamese": "trung tâm"},
   {"word": "vacancy", "type": "n", "vietnamese": "vị trí bỏ trống"},
    {"word": "tutor", "type": "n", "vietnamese": "gia sư; người hướng dẫn"},
    {"word": "hostel", "type": "n", "vietnamese": "ký túc xá; nhà trọ"},
    {"word": "perk", "type": "n", "vietnamese": "đặc quyền; lợi ích phụ"},
    {"word": "referee", "type": "n", "vietnamese": "người giới thiệu"},
    {"word": "huge", "type": "adj", "vietnamese": "to lớn"},
    {"word": "cardiac", "type": "adj", "vietnamese": "(thuộc về) tim mạch"},
    {"word": "stock", "type": "n", "vietnamese": "cổ phiếu"},
    {"word": "oversea", "type": "adj", "vietnamese": "hải ngoại; ở nước ngoài"},
    {"word": "seminar", "type": "n", "vietnamese": "hội thảo"},
   {"word": "conquer", "type": "v", "vietnamese": "chinh phục"},
    {"word": "shipbuilder", "type": "n", "vietnamese": "thợ đóng tàu"},
    {"word": "lightweight", "type": "adj", "vietnamese": "nhẹ"},
    {"word": "enroll", "type": "v", "vietnamese": "gia nhập"},
    {"word": "military", "type": "n", "vietnamese": "quân đội"},
    {"word": "hull", "type": "n", "vietnamese": "thân tàu"},
    {"word": "sail", "type": "n", "vietnamese": "cánh buồm"},
    {"word": "rower", "type": "n", "vietnamese": "người chèo"},
    {"word": "quay", "type": "n", "vietnamese": "bến tàu"},
    {"word": "drag", "type": "v", "vietnamese": "kéo"},
    {"word": "craftsman", "type": "n", "vietnamese": "thợ thủ công"},
    {"word": "plank", "type": "n", "vietnamese": "tấm ván"},
    {"word": "dominate", "type": "v", "vietnamese": "thống trị"},
    {"word": "ensure", "type": "v", "vietnamese": "đảm bảo"},
    {"word": "merchant", "type": "adj", "vietnamese": "thương mại"},
    {"word": "ship", "type": "n", "vietnamese": "tàu"},
    {"word": "reveal", "type": "v", "vietnamese": "tiết lộ"},
    {"word": "ancient", "type": "adj", "vietnamese": "cổ đại"},
    {"word": "artefact", "type": "n", "vietnamese": "hiện vật"},
    {"word": "glacier", "type": "n", "vietnamese": "sông băng"},
    {"word": "shrink", "type": "v", "vietnamese": "co lại"},
   {"word": "vanish", "type": "v", "vietnamese": "biến mất"},
    {"word": "insight", "type": "n", "vietnamese": "hiểu biết sâu sắc"},
    {"word": "decay", "type": "n", "vietnamese": "sự phân hủy"},
    {"word": "swift", "type": "adj", "vietnamese": "nhanh chóng"},
    {"word": "degradation", "type": "n", "vietnamese": "sự hư hại, sự xuống cấp"},
    {"word": "approach", "type": "n", "vietnamese": "cách tiếp cận"},
    {"word": "fieldwork", "type": "n", "vietnamese": "công tác thực địa"},
    {"word": "period", "type": "n", "vietnamese": "thời kỳ"},
    {"word": "reindeer", "type": "n", "vietnamese": "tuần lộc"},
    {"word": "congregate", "type": "v", "vietnamese": "tụ tập"},
    {"word": "settlement", "type": "n", "vietnamese": "khu định cư"},
    {"word": "stationary", "type": "adj", "vietnamese": "cố định"},
    {"word": "amid", "type": "prep", "vietnamese": "ở giữa"},
    {"word": "boulder", "type": "n", "vietnamese": "tảng đá lớn"},
    {"word": "expose", "type": "v", "vietnamese": "để lộ, phơi bày"},
    {"word": "rewarding", "type": "adj", "vietnamese": "bổ ích, đáng công"},
    {"word": "melt", "type": "v", "vietnamese": "tan chảy"},
    {"word": "survey", "type": "v", "vietnamese": "khảo sát"},
    {"word": "fragile", "type": "adj", "vietnamese": "dễ vỡ, mong manh"},
    {"word": "shift", "type": "n", "vietnamese": "sự chuyển động"},
    {"word": "spread", "type": "n", "vietnamese": "sự lan rộng"},
    {"word": "recover", "type": "v", "vietnamese": "thu hồi, phục hồi"},
    {"word": "discovery", "type": "n", "vietnamese": "khám phá"},
    {"word": "overland", "type": "adj", "vietnamese": "đường bộ"},
    {"word": "along", "type": "prep", "vietnamese": "cùng với"},
    {"word": "demand", "type": "n", "vietnamese": "nhu cầu"},
    {"word": "antler", "type": "n", "vietnamese": "gạc (sừng hươu)"}
];

export {vocab_cu1};