const vocab_cu2 = [ 
{"word": "regular", "type": "adj", "vietnamese": "đều đặn, thường xuyên"},
    {"word": "irregular", "type": "adj", "vietnamese": "không đều, không thường xuyên"},
    {"word": "bulk", "type": "n", "vietnamese": "số lượng lớn, khối lượng lớn"},
    {"word": "revenue", "type": "n", "vietnamese": "doanh thu, thu nhập"},
    {"word": "generate", "type": "v", "vietnamese": "tạo ra, phát sinh"},
    {"word": "amateur", "type": "n", "vietnamese": "(kẻ)nghiệp dư"},
    {"word": "reputation", "type": "n", "vietnamese": "danh tiếng"},
    {"word": "access", "type": "n", "vietnamese": "sự truy cập"},
    {"word": "acrobat", "type": "n", "vietnamese": "diễn viên xiếc nhào lộn"},
    {"word": "carpenter", "type": "n", "vietnamese": "thợ mộc"},
    {"word": "roundabout", "type": "n", "vietnamese": "bùng binh, vòng xuyến"},
    {"word": "junction", "type": "n", "vietnamese": "ngã ba/ngã tư, điểm giao nhau"},
    {"word": "entire", "type": "adj", "vietnamese": "toàn bộ"},
    {"word": "vogue", "type": "n", "vietnamese": "mốt, sự thịnh hành"},
    {"word": "urgent", "type": "adj", "vietnamese": "khẩn cấp"},
    {"word": "multi-storey", "type": "adj", "vietnamese": "nhiều tầng"},
    {"word": "construct", "type": "v", "vietnamese": "xây dựng"},
    {"word": "proponent", "type": "n", "vietnamese": "người ủng hộ"},
    {"word": "eventual", "type": "adj", "vietnamese": "cuối cùng"},
       {"word": "release", "type": "v", "vietnamese": "giải phóng, thải ra"},
    {"word": "stilt", "type": "n", "vietnamese": "cột chống (nhà sàn)"},
    {"word": "steep", "type": "adj", "vietnamese": "dốc"},
    {"word": "ventilation", "type": "n", "vietnamese": "sự thông gió"},
    {"word": "structure", "type": "n", "vietnamese": "kết cấu"},
    {"word": "airtight", "type": "adj", "vietnamese": "kín khí"},
    {"word": "industry", "type": "n", "vietnamese": "ngành công nghiệp"},
    {"word": "blame", "type": "v", "vietnamese": "đổ lỗi"},
    {"word": "widespread", "type": "adj", "vietnamese": "phổ biến, rộng rãi"},
    {"word": "superior", "type": "adj", "vietnamese": "vượt trội"},
    {"word": "reject", "type": "v", "vietnamese": "từ chối, bác bỏ"},
    {"word": "self-sufficient", "type": "adj", "vietnamese": "tự cung tự cấp"},
    {"word": "reflect away", "type": "v", "vietnamese": "phản xạ, phản chiếu (tia sáng)"},
    {"word": "ray", "type": "n", "vietnamese": "tia"},
    {"word": "slat", "type": "n", "vietnamese": "thanh lam, tấm bản mỏng"},
    {"word": "innovative", "type": "adj", "vietnamese": "mang tính sáng tạo, đổi mới"},
    {"word": "mould", "type": "v", "vietnamese": "nặn, đúc"},
    {"word": "insulator", "type": "n", "vietnamese": "chất cách nhiệt"},
    {"word": "rough", "type": "adj", "vietnamese": "thô ráp"},
    {"word": "frond", "type": "n", "vietnamese": "lá (cây dương xỉ, cọ)"},
    {"word": "eventual", "type": "adj", "vietnamese": "cuối cùng"},
       {"word": "acquire", "type": "v", "vietnamese": "tiếp thu, học được"},
    {"word": "cope", "type": "v", "vietnamese": "đối phó"},
    {"word": "frightening", "type": "adj", "vietnamese": "đáng sợ"},
    {"word": "physiological", "type": "adj", "vietnamese": "(thuộc) sinh lý"},
    {"word": "psychological", "type": "adj", "vietnamese": "(thuộc) tâm lý"},
    {"word": "compress", "type": "v", "vietnamese": "nén"},
    {"word": "insight", "type": "n", "vietnamese": "sự hiểu biết sâu sắc"},
    {"word": "span", "type": "n", "vietnamese": "khoảng thời gian"},
    {"word": "identify", "type": "v", "vietnamese": "nhận dạng, xác định"},
    {"word": "behavior", "type": "n", "vietnamese": "hành vi"},
    {"word": "determine", "type": "v", "vietnamese": "xác định, quyết định"},
    {"word": "proceed", "type": "v", "vietnamese": "tiến hành"},
    {"word": "stood", "type": "v", "vietnamese": "đứng (quá khứ)"},
    {"word": "cage", "type": "n", "vietnamese": "lồng"},
    {"word": "avoid", "type": "v", "vietnamese": "tránh"},
    {"word": "infant", "type": "n", "vietnamese": "trẻ sơ sinh"},
    {"word": "neutral", "type": "adj", "vietnamese": "trung lập"},
    {"word": "motionless", "type": "adj", "vietnamese": "bất động"},
    {"word": "encounter", "type": "v", "vietnamese": "gặp phải"},
    {"word": "condition", "type": "n", "vietnamese": "tình huống, điều kiện"},
    
       {"word": "hostile", "type": "adj", "vietnamese": "thù địch, hiếu chiến"},
    {"word": "overwhelm", "type": "v", "vietnamese": "làm choáng ngợp, áp đảo"},
    {"word": "terror", "type": "n", "vietnamese": "nỗi kinh hoàng, sự khiếp sợ"},
    {"word": "associate", "type": "v", "vietnamese": "liên kết, gắn với"},
    {"word": "obtain", "type": "v", "vietnamese": "đạt được, thu được"},
    {"word": "undergo", "type": "v", "vietnamese": "trải qua"},
    {"word": "cue", "type": "n", "vietnamese": "tín hiệu, dấu hiệu"},
    {"word": "elicit", "type": "v", "vietnamese": "gợi ra, khơi gợi"},
    {"word": "assume", "type": "v", "vietnamese": "cho rằng, giả định"},
    {"word": "emit", "type": "v", "vietnamese": "phát ra, bốc ra"},
    {"word": "deduce", "type": "v", "vietnamese": "suy ra, suy luận"},
    {"word": "regain", "type": "v", "vietnamese": "lấy lại, giành lại"},
    {"word": "closeness", "type": "n", "vietnamese": "sự gần gũi"},
    {"word": "extend", "type": "v", "vietnamese": "kéo dài, mở rộng"},
    {"word": "evoke", "type": "v", "vietnamese": "gợi lên"},
    {"word": "gesture", "type": "n", "vietnamese": "cử chỉ"},
    {"word": "cab", "type": "n", "vietnamese": "taxi"},
   {"word": "rent", "type": "n", "vietnamese": "thuê"},
    {"word": "hire", "type": "n", "vietnamese": "thuê"},
    {"word": "fear", "type": "n", "vietnamese": "sợ hãi"},
    {"word": "analysis", "type": "n", "vietnamese": "sự phân tích"},
    {"word": "treat", "type": "v", "vietnamese": "điều trị"},
    {"word": "solitary", "type": "adj", "vietnamese": "cô độc"},
    {"word": "peer", "type": "n", "vietnamese": "bạn cùng trang lứa"},
    {"word": "directly", "type": "adv", "vietnamese": "một cách trực tiếp"},
    {"word": "primate", "type": "n", "vietnamese": "động vật linh trưởng"},
    {"word": "gentle", "type": "adj", "vietnamese": "nhẹ nhàng"},
    {"word": "purse", "type": "v", "vietnamese": "mím (môi)"},
    {"word": "yearn", "type": "v", "vietnamese": "khao khát"},
    {"word": "spot", "type": "v", "vietnamese": "phát hiện"},
    {"word": "bark", "type": "v", "vietnamese": "sủa"},
    {"word": "force", "type": "v", "vietnamese": "ép buộc"},
    {"word": "submissive", "type": "adj", "vietnamese": "phục tùng"},
    {"word": "grimace", "type": "n", "vietnamese": "nét nhăn mặt"},
    {"word": "surmise", "type": "v", "vietnamese": "phỏng đoán"},
    {"word": "emerge", "type": "v", "vietnamese": "xuất hiện"},
    {"word": "critical", "type": "adj", "vietnamese": "then chốt"},
    {"word": "engage", "type": "v", "vietnamese": "tham gia"},
    {"word": "abdomen", "type": "n", "vietnamese": "bụng"}
];

export {vocab_cu2};