const vocab_cu3 = [
   {"word": "admire",       "type": "v",   "vietnamese": "ngưỡng mộ"},
    {"word": "volunteer",    "type": "v",   "vietnamese": "tình nguyện"},
    {"word": "army",         "type": "n",   "vietnamese": "quân đội"},
    {"word": "surgeon",      "type": "n",   "vietnamese": "bác sĩ phẫu thuật"},
    {"word": "resistance",   "type": "n",   "vietnamese": "sự kháng chiến"},
    {"word": "war",          "type": "n",   "vietnamese": "chiến tranh"},
    {"word": "diary",        "type": "n",   "vietnamese": "nhật ký"},
    {"word": "field",        "type": "n",   "vietnamese": "chiến trường"},
    {"word": "hospital",     "type": "n",   "vietnamese": "bệnh viện"},
    {"word": "account",      "type": "n",   "vietnamese": "câu chuyện"},
    {"word": "experience",   "type": "n",   "vietnamese": "trải nghiệm"},
    {"word": "enemy",        "type": "n",   "vietnamese": "kẻ thù"},
    {"word": "duty",         "type": "n",   "vietnamese": "nghĩa vụ"},
    {"word": "hero",         "type": "n",   "vietnamese": "anh hùng"},
    {"word": "devote",       "type": "v",   "vietnamese": "cống hiến"},
    {"word": "youth",        "type": "n",   "vietnamese": "tuổi trẻ"},
    {"word": "death",        "type": "n",   "vietnamese": "cái chết"},
    {"word": "attend",       "type": "v",   "vietnamese": "tham dự"},
    {"word": "childhood",    "type": "n",   "vietnamese": "tuổi thơ ấu"},
    {"word": "marriage",     "type": "n",   "vietnamese": "cuộc hôn nhân"},
    {"word": "impressive",   "type": "adj", "vietnamese": "ấn tượng"},
    {"word": "achievement",  "type": "n",   "vietnamese": "thành tựu"},
    {"word": "display",      "type": "n",   "vietnamese": "sự trưng bày"},
    {"word": "lobby",        "type": "n",   "vietnamese": "sảnh"},
    {"word": "back",         "type": "n",   "vietnamese": "mặt sau"},
    {"word": "brochure",     "type": "n",   "vietnamese": "tờ rơi"},
    {"word": "senior",       "type": "adj", "vietnamese": "lớn tuổi"},
    {"word": "avenue",       "type": "n",   "vietnamese": "đại lộ"},
    {"word": "bargain",      "type": "n",   "vietnamese": "món hời"},
   {"word": "proper", "type": "adj", "vietnamese": "đúng, phù hợp"},
    {"word": "strict", "type": "adj", "vietnamese": "nghiêm khắc"},
    {"word": "rule", "type": "n", "vietnamese": "quy tắc"},
    {"word": "obey", "type": "v", "vietnamese": "tuân theo"},
    {"word": "fragile", "type": "adj", "vietnamese": "dễ vỡ, mong manh"},
    {"word": "exhibit", "type": "v", "vietnamese": "trưng bày"},
    {"word": "hand", "type": "v", "vietnamese": "trao, đưa"},
    {"word": "out", "type": "adv", "vietnamese": "ra ngoài"},
    {"word": "interactive", "type": "adj", "vietnamese": "tương tác"},
    {"word": "layout", "type": "n", "vietnamese": "bố cục"},
    {"word": "sequence", "type": "n", "vietnamese": "trình tự"},
    {"word": "cetera", "type": "n", "vietnamese": "những thứ khác, v.v."},
    {"word": "proposal", "type": "n", "vietnamese": "đề xuất"},
    {"word": "ought to", "type": "v", "vietnamese": "nên, phải"},
    {"word": "order", "type": "n", "vietnamese": "trật tự, thứ tự"},
    {"word": "typo", "type": "n", "vietnamese": "lỗi đánh máy"},
    {"word": "knock", "type": "v", "vietnamese": "gõ, đập"},
    {"word": "cloakroom", "type": "n", "vietnamese": "phòng giữ áo mũ"},
    {"word": "insert", "type": "v", "vietnamese": "chèn vào"},
    {"word": "subheading", "type": "n", "vietnamese": "tiêu đề phụ"},
    {"word": "sake", "type": "n", "vietnamese": "mục đích, lợi ích"},
    {"word": "format", "type": "n", "vietnamese": "định dạng"},
   {"word": "description", "type": "n", "vietnamese": "sự mô tả"},  
{"word": "timekeeping", "type": "n", "vietnamese": "việc đo lường/ghi lại thời gian"},  
{"word": "invention", "type": "n", "vietnamese": "phát minh"},  
{"word": "equal", "type": "adj", "vietnamese": "bằng nhau"},  
{"word": "cabinet", "type": "n", "vietnamese": "tủ, hộp đựng"},  
{"word": "measure", "type": "v", "vietnamese": "đo lường"},  
{"word": "shadow", "type": "n", "vietnamese": "bóng, bóng râm"},  
{"word": "advent", "type": "n", "vietnamese": "sự xuất hiện, sự ra đời"},  
{"word": "satellite", "type": "n", "vietnamese": "vệ tinh"},  
{"word": "function", "type": "n", "vietnamese": "chức năng"},  
{"word": "existence", "type": "n", "vietnamese": "sự tồn tại"},  
{"word": "shape", "type": "n", "vietnamese": "hình dạng"},  
{"word": "permit", "type": "v", "vietnamese": "cho phép"},  
{"word": "pendulum", "type": "n", "vietnamese": "con lắc"},  
{"word": "split", "type": "v", "vietnamese": "chia, tách"},  
{"word": "commence", "type": "v", "vietnamese": "bắt đầu"},
    {"word": "communal", "type": "adj", "vietnamese": "chung, cộng đồng"},
    {"word": "shipment", "type": "n", "vietnamese": "việc vận chuyển"},
    {"word": "good", "type": "n", "vietnamese": "hàng hóa"},
    {"word": "harvest", "type": "v", "vietnamese": "thu hoạch"},
    {"word": "cycle", "type": "n", "vietnamese": "chu kỳ"},
    {"word": "orbit", "type": "v", "vietnamese": "quay quanh"},
    {"word": "adjust", "type": "v", "vietnamese": "điều chỉnh"},
    {"word": "maintain", "type": "v", "vietnamese": "duy trì"},
    {"word": "devise", "type": "v", "vietnamese": "phát minh, nghĩ ra"},
    {"word": "swing", "type": "v", "vietnamese": "đung đưa, dao động"},
    {"word": "anchor", "type": "n", "vietnamese": "mỏ neo"},
    {"word": "escapement", "type": "n", "vietnamese": "bộ thoát (trong đồng hồ)"},
    {"word": "lever", "type": "n", "vietnamese": "đòn bẩy, cần gạt"},
    {"word": "tooth", "type": "n", "vietnamese": "răng (bánh răng)"},
    {"word": "wheel", "type": "n", "vietnamese": "bánh xe, bánh răng"},
    {"word": "motion", "type": "n", "vietnamese": "chuyển động"},
    {"word": "rock", "type": "v", "vietnamese": "lắc, đung đưa"},
    {"word": "pendulum", "type": "n", "vietnamese": "con lắc"},
    {"word": "beat", "type": "v", "vietnamese": "dao động, nhịp"},
    {"word": "grandfather clock", "type": "n", "vietnamese": "đồng hồ quả lắc lớn kiểu cổ điển"},
    {"word": "accurate", "type": "adj", "vietnamese": "chính xác"},
    {"word": "integral", "type": "adj", "vietnamese": "không thể thiếu, cần thiết"},
    
    {"word": "Federal Aviation Administration", "type": "", "vietnamese": "Cục Hàng không Liên bang Mỹ"},
    {"word": "regulate", "type": "v", "vietnamese": "điều chỉnh, quy định"},
    {"word": "oversee", "type": "v", "vietnamese": "giám sát"},
    {"word": "operation", "type": "n", "vietnamese": "hoạt động, sự vận hành"},
    {"word": "aircraft", "type": "n", "vietnamese": "máy bay"},
    {"word": "quite", "type": "adv", "vietnamese": "khá, tương đối"},
    {"word": "congested", "type": "adj", "vietnamese": "đông đúc, tắc nghẽn"},
    {"word": "flight", "type": "n", "vietnamese": "chuyến bay"},
    {"word": "traffic", "type": "n", "vietnamese": "lưu lượng, giao thông"},
    {"word": "control", "type": "n", "vietnamese": "sự kiểm soát"},
    {"word": "advantage", "type": "n", "vietnamese": "lợi thế"},
    {"word": "communication", "type": "n", "vietnamese": "sự liên lạc"},
    {"word": "rudimentary", "type": "adj", "vietnamese": "thô sơ, sơ khai"},
    {"word": "full-scale", "type": "adj", "vietnamese": "toàn diện, quy mô đầy đủ"},
    {"word": "airspace", "type": "n", "vietnamese": "vùng trời, không phận"},
    {"word": "fortuitous", "type": "adj", "vietnamese": "tình cờ, ngẫu nhiên"},
    {"word": "jet", "type": "n", "vietnamese": "phản lực"},
    {"word": "engine", "type": "n", "vietnamese": "động cơ"},
    {"word": "margin", "type": "n", "vietnamese": "giới hạn, biên độ"},
    {"word": "consist", "type": "v", "vietnamese": "bao gồm"},
    {"word": "depart", "type": "v", "vietnamese": "rời đi, cất cánh"},
    {"word": "realise", "type": "v", "vietnamese": "nhận ra, nhận thức"},
    {"word": "element", "type": "n", "vietnamese": "yếu tố"},
    {"word": "put into effect", "type": "", "vietnamese": "thực thi, áp dụng"},
    {"word": "virtually", "type": "adv", "vietnamese": "hầu như, gần như"},
    {"word": "entire", "type": "adj", "vietnamese": "toàn bộ"},
    {"word": "blanket", "type": "v", "vietnamese": "bao phủ"},
    {"word": "vicinity", "type": "n", "vietnamese": "vùng lân cận"},
    {"word": "elsewhere", "type": "adv", "vietnamese": "nơi khác"},
    {"word": "recreational", "type": "adj", "vietnamese": "mang tính giải trí"},
    {"word": "while", "type": "n", "vietnamese": "khoảng thời gian ngắn"},
    {"word": "restriction", "type": "n", "vietnamese": "sự hạn chế"},
    {"word": "impose", "type": "v", "vietnamese": "áp đặt"},
    {"word": "below", "type": "adv", "vietnamese": "bên dưới"},
    {"word": "recognise", "type": "v", "vietnamese": "công nhận, nhận ra"},
    {"word": "reliance", "type": "n", "vietnamese": "sự phụ thuộc"},
    {"word": "navigational", "type": "adj", "vietnamese": "thuộc về định vị, dẫn đường"},
    {"word": "possess", "type": "v", "vietnamese": "sở hữu"},
    {"word": "above", "type": "adv", "vietnamese": "phía trên"},
    {"word": "beyond", "type": "adv", "vietnamese": "vượt quá"},
    {"word": "designate", "type": "v", "vietnamese": "chỉ định"},
    {"word": "letter", "type": "n", "vietnamese": "chữ cái"}
];

export {vocab_cu3};