const vocab_cu4 = [
   {"word": "establishment", "type": "n", "vietnamese": "sự thành lập"},
    {"word": "regulate", "type": "v", "vietnamese": "điều tiết, quản lý"},
    {"word": "oversee", "type": "v", "vietnamese": "giám sát"},
    {"word": "congested", "type": "adj", "vietnamese": "đông đúc, tắc nghẽn"},
    {"word": "procedure", "type": "n", "vietnamese": "thủ tục, quy trình"},
    {"word": "manually", "type": "adv", "vietnamese": "bằng tay, thủ công"},
    {"word": "purely", "type": "adv", "vietnamese": "thuần túy, hoàn toàn"},
    {"word": "rudimentary", "type": "adj", "vietnamese": "sơ khai, thô sơ"},
    {"word": "elsewhere", "type": "adv", "vietnamese": "ở nơi khác"},
    {"word": "recreational", "type": "adj", "vietnamese": "mang tính giải trí"},
    {"word": "vicinity", "type": "n", "vietnamese": "vùng lân cận"},
    {"word": "aviation", "type": "n", "vietnamese": "hàng không"},
    {"word": "commercial", "type": "adj", "vietnamese": "thương mại"},
    {"word": "operation", "type": "n", "vietnamese": "hoạt động, vận hành"},
    {"word": "govern", "type": "v", "vietnamese": "chi phối, điều chỉnh"},
    {"word": "roughly", "type": "adv", "vietnamese": "xấp xỉ, đại khái"},
    {"word": "municipal", "type": "adj", "vietnamese": "thuộc đô thị/thành phố"},
    {"word": "metropolitan", "type": "adj", "vietnamese": "thuộc đô thị lớn"},
    {"word": "compelling", "type": "adj", "vietnamese": "thuyết phục, hấp dẫn"},
    {"word": "genuine", "type": "adj", "vietnamese": "thật, xác thực"},
    {"word": "so", "type": "adv", "vietnamese": "đến mức, như vậy"},
    {"word": "far", "type": "adv", "vietnamese": "cho đến nay"},
    {"word": "suspect", "type": "v", "vietnamese": "nghi ngờ, cho rằng"},
    {"word": "detect", "type": "v", "vietnamese": "phát hiện"},
    {"word": "attitude", "type": "n", "vietnamese": "thái độ, quan điểm"},
    {"word": "telepathy", "type": "n", "vietnamese": "thần giao cách cảm"},
    {"word": "meditation", "type": "n", "vietnamese": "thiền định"},
    {"word": "indicate", "type": "v", "vietnamese": "chỉ ra, cho thấy"},
    {"word": "alter", "type": "v", "vietnamese": "thay đổi"},
    {"word": "drastically", "type": "adv", "vietnamese": "mạnh mẽ, đáng kể"},
    {"word": "trial", "type": "n", "vietnamese": "thử nghiệm"},
    {"word": "mechanism", "type": "n", "vietnamese": "cơ chế, cách thức"},
    {"word": "pose", "type": "v", "vietnamese": "đặt ra (vấn đề, khó khăn)"},
    {"word": "sealed", "type": "adj", "vietnamese": "kín, được niêm phong/cách ly"},
    {"word": "let", "type": "v", "vietnamese": "cho phép (ánh sáng/khí…) lọt vào"},
    {"word": "session", "type": "n", "vietnamese": "buổi (thí nghiệm/làm việc)"},
    {"word": "attempt", "type": "v", "vietnamese": "cố gắng"},
    {"word": "beam", "type": "v", "vietnamese": "truyền/phát (tín hiệu, hình ảnh)"},
    {"word": "implication", "type": "n", "vietnamese": "hàm ý/hệ quả kéo theo"},
    {"word": "reveal", "type": "v", "vietnamese": "tiết lộ, cho thấy"},
    {"word": "argument", "type": "n", "vietnamese": "lập luận"},
    {"word": "conventional", "type": "adj", "vietnamese": "truyền thống"},
    {"word": "rule out", "type": "phrv", "vietnamese": "loại trừ"},
    {"word": "clue", "type": "n", "vietnamese": "manh mối"},
    {"word": "reach", "type": "v", "vietnamese": "tới, truyền tới"},
    {"word": "outright", "type": "adj", "vietnamese": "trắng trợn/rõ ràng"},
    {"word": "fraud", "type": "n", "vietnamese": "sự gian lận, lừa đảo"},
    {"word": "disturbed", "type": "adj", "vietnamese": "lo ngại, băn khoăn"},
    {"word": "demand", "type": "v", "vietnamese": "đòi hỏi, yêu cầu"},
    {"word": "ignore", "type": "v", "vietnamese": "phớt lờ, bỏ qua"},
    {"word": "statistical", "type": "adj", "vietnamese": "thuộc thống kê"},
    {"word": "apparent", "type": "adj", "vietnamese": "rõ ràng, dễ thấy"},
    {"word": "seem", "type": "v", "vietnamese": "dường như"},
    {"word": "stem", "type": "v", "vietnamese": "bắt nguồn (từ)"},
    {"word": "plausible", "type": "adj", "vietnamese": "hợp lý, có vẻ đúng"},
    {"word": "already", "type": "adv", "vietnamese": "đã, sẵn"},
    {"word": "particularly", "type": "adv", "vietnamese": "đặc biệt là"},
    {"word": "eventually", "type": "adv", "vietnamese": "cuối cùng thì"},
    {"word": "existence", "type": "n", "vietnamese": "sự tồn tại"},
    {"word": "subject to", "type": "phrv", "vietnamese": "cho (ai/cái gì) trải qua (điều gì đó)"},
    {"word": "put down to", "type": "phrv", "vietnamese": "quy cho (cái gì đó)"},
       {"word": "present", "type": "v", "vietnamese": "trình bày"},
    {"word": "finding", "type": "n", "vietnamese": "phát hiện, kết quả nghiên cứu"},
    {"word": "extra", "type": "adj", "vietnamese": "thêm, bổ sung"},
    {"word": "funding", "type": "n", "vietnamese": "kinh phí, tài trợ"},
    {"word": "preference", "type": "n", "vietnamese": "sự ưa thích, lựa chọn"},
    {"word": "colleague", "type": "n", "vietnamese": "đồng nghiệp"},
    {"word": "refuse", "type": "v", "vietnamese": "từ chối"},
    {"word": "confidentiality", "type": "n", "vietnamese": "tính bảo mật"},
    {"word": "anticipate", "type": "v", "vietnamese": "dự đoán, mong đợi"},
    {"word": "unwillingness", "type": "n", "vietnamese": "sự không sẵn lòng"},
    {"word": "taken aback", "type": "phrv", "vietnamese": "bị bất ngờ, choáng váng"},
    {"word": "department", "type": "n", "vietnamese": "khoa, phòng ban"},
    {"word": "pull out", "type": "phrv", "vietnamese": "rút lui, bỏ cuộc"},
    {"word": "interview", "type": "v", "vietnamese": "phỏng vấn"},
    {"word": "reassurance", "type": "n", "vietnamese": "sự trấn an"},
    {"word": "traceable", "type": "adj", "vietnamese": "có thể truy ra, lần theo được"},
    {"word": "bizarre", "type": "adj", "vietnamese": "kỳ quái, kỳ lạ"},
    {"word": "substance", "type": "n", "vietnamese": "chất (hóa học; vật chất)"},
   {"word": "estate agent", "type": "n", "vietnamese": "nhân viên môi giới bất động sản"},
{"word": "consist of", "type": "phrv", "vietnamese": "bao gồm, gồm có"},
{"word": "per year", "type": "", "vietnamese": "mỗi năm, theo năm"},

{"word": "venue", "type": "n", "vietnamese": "địa điểm tổ chức sự kiện"},
{"word": "exhibition", "type": "n", "vietnamese": "cuộc triển lãm"},
{"word": "intend", "type": "v", "vietnamese": "dự định, có ý định"},
{"word": "get involved in", "type": "", "vietnamese": "tham gia/dính líu vào"},
{"word": "find", "type": "v", "vietnamese": "nhận thấy/cảm thấy (find + object + adj)"},
{"word": "wisely", "type": "adv", "vietnamese": "một cách khôn ngoan"},
{"word": "contract", "type": "n", "vietnamese": "hợp đồng"},
{"word": "acquisition", "type": "n", "vietnamese": "sự tiếp thu (kiến thức/kỹ năng)"},
{"word": "indigenous", "type": "adj", "vietnamese": "bản địa, thuộc thổ dân"},
{"word": "Portuguese", "type": "adj", "vietnamese": "thuộc về/tiếng Bồ Đào Nha"},

{"word": "spotlight", "type": "n", "vietnamese": "tiêu điểm (ánh đèn sân khấu)"},
{"word": "already", "type": "adv", "vietnamese": "đã, sớm hơn mong đợi"},
{"word": "actually", "type": "adv", "vietnamese": "thực ra, thật sự"},
{"word": "cater", "type": "v", "vietnamese": "cung cấp dịch vụ/đáp ứng nhu cầu"},
{"word": "enormous", "type": "adj", "vietnamese": "rất lớn, khổng lồ"},
{"word": "broadcast", "type": "n", "vietnamese": "chương trình phát sóng"},
{"word": "spectacular", "type": "adj", "vietnamese": "ngoạn mục, ấn tượng"},
{"word": "statement", "type": "n", "vietnamese": "bản tuyên bố, lời phát biểu"},
{"word": "combine", "type": "v", "vietnamese": "kết hợp"},
{"word": "agency", "type": "n", "vietnamese": "cơ quan, hãng dịch vụ"},
{"word": "whether", "type": "", "vietnamese": "liệu rằng, liệu có… hay không"},
{"word": "proper", "type": "adj", "vietnamese": "đúng mực, thích hợp"},
{"word": "demotivated", "type": "adj", "vietnamese": "mất động lực"},
{"word": "otherwise", "type": "adv", "vietnamese": "nếu không thì"},
{"word": "suspicious", "type": "adj", "vietnamese": "nghi ngờ, cảnh giác"},
{"word": "administration", "type": "n", "vietnamese": "công tác quản trị, ban quản lý"},
{"word": "definite", "type": "adj", "vietnamese": "chắc chắn, dứt khoát"},
   {"word": "molten", "type": "adj", "vietnamese": "nóng chảy"},
{"word": "mass", "type": "n", "vietnamese": "khối vật chất"},
{"word": "clear", "type": "adj", "vietnamese": "trong suốt"},
{"word": "flat", "type": "adj", "vietnamese": "phẳng"},
{"word": "unblemished", "type": "adj", "vietnamese": "không tì vết"},
{"word": "labour", "type": "n", "vietnamese": "lao động"},
{"word": "intensive", "type": "adj", "vietnamese": "cường độ cao"},
{"word": "squeeze", "type": "v", "vietnamese": "ép"},
{"word": "mangle", "type": "n", "vietnamese": "máy ép (con lăn)"},
{"word": "virtually", "type": "adv", "vietnamese": "hầu như"},
{"word": "thickness", "type": "n", "vietnamese": "độ dày"},
{"word": "mark", "type": "v", "vietnamese": "để lại vết"},
{"word": "coat", "type": "v", "vietnamese": "phủ bề mặt"},
{"word": "tint", "type": "v", "vietnamese": "nhuộm màu nhạt"},
{"word": "glass", "type": "n", "vietnamese": "kính"},
{"word": "eliminate", "type": "v", "vietnamese": "loại bỏ"},
{"word": "boil", "type": "v", "vietnamese": "sôi"},
{"word": "tin", "type": "n", "vietnamese": "thiếc"},
{"word": "concept", "type": "n", "vietnamese": "khái niệm"},
{"word": "guarantee", "type": "v", "vietnamese": "bảo đảm"},
{"word": "horizontal", "type": "adj", "vietnamese": "nằm ngang"},
{"word": "pour", "type": "v", "vietnamese": "đổ"},
{"word": "parallel", "type": "adj", "vietnamese": "song song"},
{"word": "settle", "type": "v", "vietnamese": "ổn định"},
{"word": "tension", "type": "n", "vietnamese": "sức căng (bề mặt)"},
{"word": "fortunate", "type": "adj", "vietnamese": "may mắn"},
{"word": "coincidence", "type": "n", "vietnamese": "sự trùng hợp"},
{"word": "convince", "type": "v", "vietnamese": "thuyết phục"},
{"word": "optical", "type": "adj", "vietnamese": "quang học"},
{"word": "refine", "type": "v", "vietnamese": "tinh luyện"},
{"word": "homogenise", "type": "v", "vietnamese": "làm đồng nhất"},
{"word": "simultaneously", "type": "adv", "vietnamese": "đồng thời"},
{"word": "relieve", "type": "v", "vietnamese": "làm giảm"},
{"word": "principle", "type": "n", "vietnamese": "nguyên lý"},
{"word": "mar", "type": "v", "vietnamese": "làm hỏng"},
{"word": "inclusion", "type": "n", "vietnamese": "tạp chất"},
{"word": "bubble", "type": "n", "vietnamese": "bọt khí"},
{"word": "inspection", "type": "n", "vietnamese": "kiểm tra"},
{"word": "occasionally", "type": "adv", "vietnamese": "thỉnh thoảng"},
{"word": "grain", "type": "n", "vietnamese": "hạt"},
{"word": "tremor", "type": "n", "vietnamese": "rung nhẹ"},
{"word": "ripple", "type": "n", "vietnamese": "gợn sóng"},
{"word": "reveal", "type": "v", "vietnamese": "phát hiện"},
{"word": "fault", "type": "n", "vietnamese": "lỗi"},
{"word": "upstream", "type": "adv", "vietnamese": "ở đầu quy trình"},
{"word": "flaw", "type": "n", "vietnamese": "khuyết tật"},
{"word": "unaided", "type": "adj", "vietnamese": "không được hỗ trợ"},
{"word": "downstream", "type": "adv", "vietnamese": "ở giai đoạn sau"},
{"word": "steer", "type": "v", "vietnamese": "điều khiển"},
{"word": "cutter", "type": "n", "vietnamese": "dao cắt"},
{"word": "pattern", "type": "n", "vietnamese": "mẫu (cắt)"},
{"word": "property", "type": "n", "vietnamese": "tính chất"},
{"word": "plant", "type": "n", "vietnamese": "nhà máy"},
{"word": "full-scale", "type": "adj", "vietnamese": "quy mô đầy đủ"},
{"word": "instant", "type": "adj", "vietnamese": "tức thì"},
{"word": "commercial", "type": "adj", "vietnamese": "thương mại"},
{"word": "improve", "type": "v", "vietnamese": "cải tiến"},
{"word": "detect", "type": "v", "vietnamese": "phát hiện"}
   ];

    export {vocab_cu4};