
const vocabListKhiem = [
    {"word": "embark", "type": "v", "vietnamese": "bắt đầu; dấn thân (vào)"},
    {"word": "context", "type": "n", "vietnamese": "bối cảnh"},
    {"word": "mercy", "type": "n", "vietnamese": "sự phó mặc; chịu sự chi phối"},
    {"word": "episode", "type": "n", "vietnamese": "đợt; giai đoạn"},
    {"word": "ancestor", "type": "n", "vietnamese": "tổ tiên"},
    {"word": "suffering", "type": "n", "vietnamese": "sự đau khổ"},
    {"word": "cycle", "type": "n", "vietnamese": "chu kỳ"},
    {"word": "bitterly", "type": "adv", "vietnamese": "buốt giá; vô cùng (lạnh)"},
    {"word": "unprecedented", "type": "adj", "vietnamese": "chưa từng có"},
    {"word": "seesaw", "type": "n", "vietnamese": "trạng thái dao động/bập bênh"},
    {"word": "last", "type": "v", "vietnamese": "kéo dài"},
    {"word": "quarter", "type": "n", "vietnamese": "một phần tư"},
    {"word": "century", "type": "n", "vietnamese": "thế kỷ"},
    {"word": "intensely", "type": "adv", "vietnamese": "cực kỳ; mãnh liệt"},
    {"word": "easterly", "type": "adj", "vietnamese": "thổi từ hướng đông"},
    {"word": "abruptly", "type": "adv", "vietnamese": "đột ngột"},
    {"word": "mild", "type": "adj", "vietnamese": "ôn hòa; ấm áp (khí hậu)"},
    {"word": "reconstruct", "type": "v", "vietnamese": "tái dựng; phục dựng"},
    {"word": "systematic", "type": "adj", "vietnamese": "có hệ thống"},
    {"word": "hemisphere", "type": "n", "vietnamese": "bán cầu"},
    {"word": "narrative", "type": "adj", "vietnamese": "mang tính tường thuật"},
    {"word": "voyager", "type": "n", "vietnamese": "người du hành (biển)"},
    {"word": "reroute", "type": "v", "vietnamese": "đổi tuyến; chuyển lộ trình"},
    {"word": "wet", "type": "adj", "vietnamese": "ẩm ướt; nhiều mưa"},
    {"word": "descend", "type": "v", "vietnamese": "kéo đến; trùm xuống"},
    {"word": "famine", "type": "n", "vietnamese": "nạn đói"},
    {"word": "culminate", "type": "v", "vietnamese": "đạt/đến đỉnh điểm"},
    {"word": "commodity", "type": "n", "vietnamese": "hàng hóa; mặt hàng thiết yếu"},
    {"word": "constant", "type": "adj", "vietnamese": "liên tục; thường xuyên"},
    {"word": "cod", "type": "n", "vietnamese": "cá tuyết"},
    {"word": "herring", "type": "n", "vietnamese": "cá trích"},
    {"word": "offshore", "type": "adj", "vietnamese": "ngoài khơi; xa bờ"},
    {"word": "fodder", "type": "n", "vietnamese": "thức ăn gia súc"},
    {"word": "grain", "type": "n", "vietnamese": "ngũ cốc; thóc lúa"},
    {"word": "livestock", "type": "n", "vietnamese": "gia súc"},
    {"word": "migration", "type": "n", "vietnamese": "sự di cư"},
    {"word": "blight", "type": "n", "vietnamese": "bệnh tàn lụi; bệnh sương mai (cây trồng)"},
    {"word": "clearance", "type": "n", "vietnamese": "việc phát quang/chặt phá (rừng)"},
    {"word": "trigger", "type": "v", "vietnamese": "kích hoạt; gây ra"},
    {"word": "regime", "type": "n", "vietnamese": "chế độ (khí hậu)"},
    {"word": "prolonged", "type": "adj", "vietnamese": "kéo dài; dai dẳng"},

    {"word": "olfaction", "type": "n", "vietnamese": "khứu giác"},
    {"word": "apparent", "type": "adj", "vietnamese": "rõ ràng; hiển nhiên"},
    {"word": "evoke", "type": "v", "vietnamese": "gợi lên; khơi gợi"},
    {"word": "odour", "type": "n", "vietnamese": "mùi (hương/khí)"},
    {"word": "grimace", "type": "v", "vietnamese": "nhăn mặt (tỏ vẻ khó chịu)"},
    {"word": "disgust", "type": "n", "vietnamese": "sự ghê tởm; kinh tởm"},
    {"word": "olfactory", "type": "adj", "vietnamese": "thuộc khứu giác"},
    {"word": "label", "type": "v", "vietnamese": "gán nhãn; gọi là"},
    {"word": "unpleasant", "type": "adj", "vietnamese": "khó chịu; hôi hám"},
    {"word": "fragrant", "type": "adj", "vietnamese": "thơm; thơm ngát"},
    {"word": "bonding", "type": "n", "vietnamese": "sự gắn kết (tình cảm/xã hội)"},
    {"word": "spouse", "type": "n", "vietnamese": "vợ/chồng"},
    {"word": "distinguish", "type": "v", "vietnamese": "phân biệt; nhận ra"},
    {"word": "feeble", "type": "adj", "vietnamese": "yếu ớt; kém (khả năng)"},
    {"word": "elusive", "type": "adj", "vietnamese": "khó nắm bắt; mơ hồ"},
    {"word": "undertake", "type": "v", "vietnamese": "tiến hành; thực hiện"},
    {"word": "nonphysical", "type": "adj", "vietnamese": "phi vật chất; không thuộc vật lý"},
    {"word": "component", "type": "n", "vietnamese": "thành phần"},
    {"word": "inevitably", "type": "adv", "vietnamese": "tất yếu; không tránh khỏi"},
    {"word": "intimate", "type": "adj", "vietnamese": "thân mật; gần gũi"},
    {"word": "interiorise", "type": "v", "vietnamese": "nội tâm hóa; thấm nhuần"},
    {"word": "essence", "type": "n", "vietnamese": "bản chất; cốt lõi"},
    {"word": "interpretation", "type": "n", "vietnamese": "sự diễn giải; cách hiểu"}
];

export {vocabListKhiem};