const vocab_truong = [
   {"word": "awareness", "type": "n", "vietnamese": "sự nhận thức"},
    {"word": "carbon footprint", "type": "n", "vietnamese": "tổng lượng phát thải khí CO2"},
    {"word": "resource", "type": "n", "vietnamese": "nguồn tài nguyên"},
    {"word": "efficiently", "type": "adv", "vietnamese": "một cách hiệu quả"},
    {"word": "eco-friendly", "type": "adj", "vietnamese": "thân thiện với môi trường"},
    {"word": "decompose", "type": "v", "vietnamese": "phân hủy"},
    {"word": "reusable", "type": "adj", "vietnamese": "có thể tái sử dụng"},
    {"word": "single-use", "type": "adj", "vietnamese": "dùng một lần"},
    {"word": "ecotourism", "type": "n", "vietnamese": "du lịch sinh thái"},
    {"word": "waste", "type": "n", "vietnamese": "rác thải"},
    {"word": "landfill", "type": "n", "vietnamese": "bãi rác"},
    {"word": "reuse", "type": "v", "vietnamese": "tái sử dụng"},
    {"word": "packaging", "type": "n", "vietnamese": "bao bì"},
    {"word": "container", "type": "n", "vietnamese": "hộp, gói, thùng chứa"},
    {"word": "recyclable", "type": "adj", "vietnamese": "có thể tái chế"},
    {"word": "cardboard", "type": "n", "vietnamese": "bia cứng"},
    {"word": "cardboard", "type": "adj", "vietnamese": "làm bằng bìa cứng"},
    {"word": "leftover", "type": "n", "vietnamese": "thức ăn thừa"},
    {"word": "contaminated", "type": "adj", "vietnamese": "nhiễm độc, nhiễm khuẩn"},
    {"word": "compost", "type": "n", "vietnamese": "phân hữu cơ"},
    {"word": "sort", "type": "v", "vietnamese": "phân loại"},
    {"word": "layer", "type": "n", "vietnamese": "tầng, lớp"},
    {"word": "household waste", "type": "n", "vietnamese": "rác thải sinh hoạt"},
    {"word": "fruit peel", "type": "n", "vietnamese": "vỏ hoa quả"},
    {"word": "pile", "type": "n", "vietnamese": "đống"},
    {"word": "recycle", "type": "v", "vietnamese": "tái chế"},
    {"word": "sustainable", "type": "adj", "vietnamese": "bền vững, thân thiện môi trường"},
    {"word": "release", "type": "v", "vietnamese": "thải ra"},
   {"word": "multicultural", "type": "adj", "vietnamese": "đa văn hóa"},
    {"word": "cultural diversity", "type": "n", "vietnamese": "đa dạng văn hóa"},
    {"word": "cuisine", "type": "n", "vietnamese": "ẩm thực"},
    {"word": "booth", "type": "n", "vietnamese": "gian hàng"},
    {"word": "spicy", "type": "adj", "vietnamese": "cay"},
    {"word": "autograph", "type": "n", "vietnamese": "chữ ký của người nổi tiếng"},
    {"word": "souvenir", "type": "n", "vietnamese": "đồ lưu niệm"},
    {"word": "tug of war", "type": "n", "vietnamese": "trò chơi kéo co"},
    {"word": "bamboo dancing", "type": "n", "vietnamese": "nhảy sạp"},
    {"word": "delicious", "type": "adj", "vietnamese": "ngon miệng"},
    {"word": "identity", "type": "n", "vietnamese": "bản sắc, đặc điểm nhận dạng"},
    {"word": "origin", "type": "n", "vietnamese": "nguồn gốc"},
    {"word": "popularity", "type": "n", "vietnamese": "sự phổ biến"},
    {"word": "festival", "type": "n", "vietnamese": "lễ hội"},
    {"word": "trend", "type": "n", "vietnamese": "xu hướng"},
    {"word": "custom", "type": "n", "vietnamese": "phong tục"},
    {"word": "mystery", "type": "n", "vietnamese": "điều bí ẩn"},
    {"word": "globalisation", "type": "n", "vietnamese": "toàn cầu hóa"},
    {"word": "connected", "type": "adj", "vietnamese": "kết nối"},
    {"word": "respect", "type": "n", "vietnamese": "khía cạnh"},
    {"word": "dish", "type": "n", "vietnamese": "món ăn"},
    {"word": "ingredient", "type": "n", "vietnamese": "nguyên liệu, thành phần"},
    {"word": "unique", "type": "adj", "vietnamese": "độc đáo"},
    {"word": "specialty", "type": "n", "vietnamese": "đặc sản"},
    {"word": "captivate", "type": "v", "vietnamese": "thu hút, lôi cuốn"},
    {"word": "cross-cultural", "type": "adj", "vietnamese": "giao thoa văn hóa"},
    {"word": "blend", "type": "v", "vietnamese": "pha trộn"},
    {"word": "reflect", "type": "v", "vietnamese": "phản ánh"},
    {"word": "richness", "type": "n", "vietnamese": "sự phong phú"},
    {"word": "appreciate", "type": "v", "vietnamese": "thưởng thức, trân trọng"},
    {"word": "lifestyle", "type": "n", "vietnamese": "lối sống"},
    {"word": "celebrate", "type": "v", "vietnamese": "tổ chức, ăn mừng"},
   {"word": "admire", "type": "v", "vietnamese": "ngưỡng mộ"},
    {"word": "volunteer", "type": "v", "vietnamese": "tình nguyện"},
    {"word": "army", "type": "n", "vietnamese": "quân đội"},
    {"word": "surgeon", "type": "n", "vietnamese": "bác sĩ phẫu thuật"},
    {"word": "resistance war", "type": "n", "vietnamese": "cuộc kháng chiến"},
    {"word": "diary", "type": "n", "vietnamese": "nhật ký"},
    {"word": "field hospital", "type": "n", "vietnamese": "bệnh viện dã chiến"},
    {"word": "account", "type": "n", "vietnamese": "câu chuyện"},
    {"word": "experience", "type": "n", "vietnamese": "trải nghiệm"},
    {"word": "enemy", "type": "n", "vietnamese": "kẻ thù"},
    {"word": "duty", "type": "n", "vietnamese": "nghĩa vụ, nhiệm vụ"},
    {"word": "hero", "type": "n", "vietnamese": "anh hùng"},
    {"word": "devote", "type": "v", "vietnamese": "cống hiến"},
    {"word": "youth", "type": "n", "vietnamese": "tuổi trẻ"},
    {"word": "death", "type": "n", "vietnamese": "cái chết"},
    {"word": "attend", "type": "v", "vietnamese": "đi học, tham dự"},
    {"word": "childhood", "type": "n", "vietnamese": "tuổi thơ ấu"},
    {"word": "marriage", "type": "n", "vietnamese": "cuộc hôn nhân"},
    {"word": "impressive", "type": "adj", "vietnamese": "đầy ấn tượng"},
    {"word": "achievement", "type": "n", "vietnamese": "thành tựu"},
    {"word": "biological", "type": "adj", "vietnamese": "ruột thịt"},
    {"word": "adopt", "type": "v", "vietnamese": "nhận con nuôi"},
    {"word": "bond", "type": "n", "vietnamese": "kết thân, kết nối"},
    {"word": "accessible", "type": "adj", "vietnamese": "dễ tiếp cận"},
    {"word": "touchscreen", "type": "n", "vietnamese": "màn hình cảm ứng"},
    {"word": "cutting-edge", "type": "adj", "vietnamese": "hiện đại"},
    {"word": "stylish", "type": "adj", "vietnamese": "kiểu cách"},
    {"word": "animated", "type": "adj", "vietnamese": "hoạt hình"},
    {"word": "blockbuster", "type": "n", "vietnamese": "phim bom tấn"},
    {"word": "diagnose", "type": "v", "vietnamese": "chẩn đoán"},
    {"word": "rare", "type": "adj", "vietnamese": "hiếm"},
    {"word": "cancer", "type": "n", "vietnamese": "ung thư"}
];
export {vocab_truong};